/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteTestEntityArgs } from "./DeleteTestEntityArgs";
import { TestEntityCountArgs } from "./TestEntityCountArgs";
import { TestEntityFindManyArgs } from "./TestEntityFindManyArgs";
import { TestEntityFindUniqueArgs } from "./TestEntityFindUniqueArgs";
import { TestEntity } from "./TestEntity";
import { TestEntityService } from "../testEntity.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => TestEntity)
export class TestEntityResolverBase {
  constructor(
    protected readonly service: TestEntityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "TestEntity",
    action: "read",
    possession: "any",
  })
  async _testEntitiesMeta(
    @graphql.Args() args: TestEntityCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [TestEntity])
  @nestAccessControl.UseRoles({
    resource: "TestEntity",
    action: "read",
    possession: "any",
  })
  async testEntities(
    @graphql.Args() args: TestEntityFindManyArgs
  ): Promise<TestEntity[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => TestEntity, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "TestEntity",
    action: "read",
    possession: "own",
  })
  async testEntity(
    @graphql.Args() args: TestEntityFindUniqueArgs
  ): Promise<TestEntity | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TestEntity)
  @nestAccessControl.UseRoles({
    resource: "TestEntity",
    action: "delete",
    possession: "any",
  })
  async deleteTestEntity(
    @graphql.Args() args: DeleteTestEntityArgs
  ): Promise<TestEntity | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
